import fs from "node:fs";
const NL = String.fromCharCode(10);
const Q = String.fromCharCode(39);
const DQ = String.fromCharCode(34);
let s = fs.readFileSync("assets/app.js", "utf8");

const pStart = s.indexOf("function printDoc(title,html){");
const pEnd = s.indexOf("function backup(){");
const newPrint = [
"function printHead(title,sub){",
"  var org=(DB&&DB.prefs&&DB.prefs.org)||{name:" + Q + "Gorgan Horse Federation" + Q + ",code:" + Q + "IR-GHF-1404" + Q + "};",
"  return " + Q + "<div class=" + DQ + "ghf-print-head" + DQ + "><div class=" + DQ + "ghf-print-seal" + DQ + ">GHF</div><div style=" + DQ + "flex:1" + DQ + ">" + Q + "+",
"    " + Q + "<div style=" + DQ + "font-weight:700;font-size:15px" + DQ + ">" + Q + "+esc(org.name)+" + Q + "</div>" + Q + "+",
"    " + Q + "<div style=" + DQ + "font-size:11px;color:#555" + DQ + ">" + Q + "+esc(org.code)+(" + Q + " · printed " + Q + ")+nowISO()+" + Q + "</div>" + Q + "+",
"    " + Q + "<div style=" + DQ + "font-weight:700;font-size:19px;margin-top:6px" + DQ + ">" + Q + "+esc(title)+" + Q + "</div>" + Q + "+",
"    (sub?" + Q + "<div style=" + DQ + "font-size:11.5px;color:#666;margin-top:2px" + DQ + ">" + Q + "+esc(sub)+" + Q + "</div>" + Q + ":" + Q + "" + Q + ")+",
"    " + Q + "</div></div>" + Q + ";",
"}",
"function printDoc(title,html,sub){",
"  var inner=printHead(title,sub)+html;",
"  var foot=" + Q + "<div class=" + DQ + "ghf-print-foot" + DQ + ">" + Q + "+((DB&&DB.prefs&&DB.prefs.org&&DB.prefs.org.name)||" + Q + "Gorgan Horse Federation" + Q + ")+" + Q + " · " + Q + "+nowISO()+" + Q + " · This document is generated by the federation registry system.</div>" + Q + ";",
"  $( " + Q + "#printArea" + Q + " ).innerHTML=inner+foot;",
"  openModal('<div class=" + DQ + "pad" + DQ + " style=" + DQ + "border-bottom:1px solid var(--border)" + DQ + "><div class=" + DQ + "row jb gap3" + DQ + "><div class=" + DQ + "g1" + DQ + "><h3 class=" + DQ + "dsp bb" + DQ + " style=" + DQ + "font-size:17px" + DQ + ">'+esc(title)+'</h3><p class=" + DQ + "mut i12 mt1" + DQ + ">'+esc(T("Document preview"))+'</p></div><button class=" + DQ + "btn-i" + DQ + " data-action=" + DQ + "ui.closeModal" + DQ + ">'+ic("i-x","")+'</button></div></div>'+",
"    '<div class=" + DQ + "pad scroll" + DQ + " style=" + DQ + "max-height:56vh;overflow:auto;background:var(--surface-2)" + DQ + "><div class=" + DQ + "panel pad" + DQ + " style=" + DQ + "box-shadow:none;background:#fff" + DQ + ">'+inner+foot+'</div></div>'+",
"    '<div class=" + DQ + "pad row jend gap2" + DQ + " style=" + DQ + "border-top:1px solid var(--border)" + DQ + "><button class=" + DQ + "btn btn-g" + DQ + " data-action=" + DQ + "ui.closeModal" + DQ + ">'+esc(T("Close"))+'</button><button class=" + DQ + "btn btn-p" + DQ + " data-action=" + DQ + "ui.printNow" + DQ + ">'+ic("i-print","")+' '+esc(T("Print"))+' / PDF</button></div>','780px');",
"}",
""
].join(NL);
s = s.slice(0, pStart) + newPrint + s.slice(pEnd);
fs.writeFileSync("assets/app.js", s, "utf8");
console.log("printDoc replaced");
