import fs from 'node:fs';
const NL = String.fromCharCode(10);
const Q = String.fromCharCode(39);
const DQ = String.fromCharCode(34);
let s = fs.readFileSync('assets/app.js','utf8');

// helper block injected right after clamp()
const helpers = [
'',
'/* ============================== i18n + UX HELPERS ============================== */',
'function T(s){return (window.I18N&&I18N.t)?I18N.t(s):s;}',
'function fmtD(iso){return (window.I18N&&I18N.fmtDate)?I18N.fmtDate(iso):(iso||String.fromCharCode(8212));}',
'function fmtDL(iso){return (window.I18N&&I18N.fmtDateLong)?I18N.fmtDateLong(iso):(iso||String.fromCharCode(8212));}',
'function NX(v){return (window.I18N&&I18N.num)?I18N.num(v):n(v);}',
'function tip(txt){var t=T(txt);return String.fromCharCode(32)+String.fromCharCode(60)+String.fromCharCode(115)+String.fromCharCode(112)+String.fromCharCode(97)+String.fromCharCode(110)+String.fromCharCode(32)+String.fromCharCode(99)+String.fromCharCode(108)+String.fromCharCode(97)+String.fromCharCode(115)+String.fromCharCode(115)+String.fromCharCode(61)+DQ+String.fromCharCode(113)+String.fromCharCode(109)+String.fromCharCode(97)+String.fromCharCode(114)+String.fromCharCode(107)+DQ+String.fromCharCode(32)+String.fromCharCode(100)+String.fromCharCode(97)+String.fromCharCode(116)+String.fromCharCode(97)+String.fromCharCode(45)+String.fromCharCode(116)+String.fromCharCode(105)+String.fromCharCode(112)+String.fromCharCode(61)+DQ+esc(t)+DQ+String.fromCharCode(62)+String.fromCharCode(60)+String.fromCharCode(47)+String.fromCharCode(115)+String.fromCharCode(112)+String.fromCharCode(97)+String.fromCharCode(110)+String.fromCharCode(62);}',
'function thCell(label,txt,key,dir,act){var ind=key?String.fromCharCode(60)+String.fromCharCode(115)+String.fromCharCode(112)+String.fromCharCode(97)+String.fromCharCode(110)+String.fromCharCode(32)+String.fromCharCode(99)+String.fromCharCode(108)+String.fromCharCode(97)+String.fromCharCode(115)+String.fromCharCode(115)+DQ+String.fromCharCode(32)+String.fromCharCode(115)+String.fromCharCode(111)+String.fromCharCode(114)+String.fromCharCode(116)+String.fromCharCode(105)+String.fromCharCode(110)+String.fromCharCode(100)+DQ+String.fromCharCode(62)+(dir>0?String.fromCharCode(9650):String.fromCharCode(9660))+String.fromCharCode(60)+String.fromCharCode(47)+String.fromCharCode(115)+String.fromCharCode(112)+String.fromCharCode(97)+String.fromCharCode(110)+String.fromCharCode(62):String.fromCharCode(34)+String.fromCharCode(34);var cl=String.fromCharCode(116)+String.fromCharCode(104)+(key?String.fromCharCode(32)+String.fromCharCode(115)+String.fromCharCode(111)+String.fromCharCode(114)+String.fromCharCode(116)+String.fromCharCode(97)+String.fromCharCode(98)+String.fromCharCode(108)+String.fromCharCode(101):String.fromCharCode(34)+String.fromCharCode(34));return String.fromCharCode(60)+String.fromCharCode(116)+String.fromCharCode(104)+String.fromCharCode(32)+String.fromCharCode(99)+String.fromCharCode(108)+String.fromCharCode(97)+String.fromCharCode(115)+String.fromCharCode(115)+String.fromCharCode(61)+String.fromCharCode(34)+cl+String.fromCharCode(34)+(key?String.fromCharCode(32)+String.fromCharCode(100)+String.fromCharCode(97)+String.fromCharCode(116)+String.fromCharCode(97)+String.fromCharCode(45)+String.fromCharCode(115)+String.fromCharCode(111)+String.fromCharCode(114)+String.fromCharCode(116)+String.fromCharCode(61)+String.fromCharCode(34)+key+String.fromCharCode(34)+String.fromCharCode(32)+String.fromCharCode(100)+String.fromCharCode(97)+String.fromCharCode(116)+String.fromCharCode(97)+String.fromCharCode(45)+String.fromCharCode(97)+String.fromCharCode(99)+String.fromCharCode(116)+String.fromCharCode(61)+String.fromCharCode(34)+(act||String.fromCharCode(117)+String.fromCharCode(105)+String.fromCharCode(46)+String.fromCharCode(115)+String.fromCharCode(111)+String.fromCharCode(114)+String.fromCharCode(116))+String.fromCharCode(34):String.fromCharCode(34)+String.fromCharCode(34))+String.fromCharCode(62)+T(label)+tip(txt)+ind+String.fromCharCode(60)+String.fromCharCode(47)+String.fromCharCode(116)+String.fromCharCode(104)+String.fromCharCode(62);}',
'function reportBtn(txt,act,extra){return String.fromCharCode(60)+String.fromCharCode(98)+String.fromCharCode(117)+String.fromCharCode(116)+String.fromCharCode(116)+String.fromCharCode(111)+String.fromCharCode(110)+String.fromCharCode(32)+String.fromCharCode(99)+String.fromCharCode(108)+String.fromCharCode(97)+String.fromCharCode(115)+String.fromCharCode(115)+String.fromCharCode(61)+String.fromCharCode(34)+String.fromCharCode(98)+String.fromCharCode(116)+String.fromCharCode(110)+String.fromCharCode(32)+String.fromCharCode(98)+String.fromCharCode(116)+String.fromCharCode(110)+String.fromCharCode(45)+String.fromCharCode(103)+String.fromCharCode(34)+String.fromCharCode(32)+String.fromCharCode(100)+String.fromCharCode(97)+String.fromCharCode(116)+String.fromCharCode(97)+String.fromCharCode(45)+String.fromCharCode(97)+String.fromCharCode(99)+String.fromCharCode(116)+String.fromCharCode(105)+String.fromCharCode(111)+String.fromCharCode(110)+String.fromCharCode(61)+String.fromCharCode(34)+act+String.fromCharCode(34)+String.fromCharCode(62)+T(txt)+String.fromCharCode(60)+String.fromCharCode(47)+String.fromCharCode(98)+String.fromCharCode(117)+String.fromCharCode(116)+String.fromCharCode(116)+String.fromCharCode(111)+String.fromCharCode(110)+String.fromCharCode(62);}',
'function sortList(arr,key,dir){if(!key)return arr;return arr.slice().sort(function(a,b){var x=a[key],y=b[key];if(typeof x===String.fromCharCode(110)+String.fromCharCode(117)+String.fromCharCode(109)+String.fromCharCode(98)+String.fromCharCode(101)+String.fromCharCode(114))return (x-y)*dir;return String(x).localeCompare(String(y))*dir;});}',
'',
].join(NL);

const anchor = String.fromCharCode(102)+String.fromCharCode(117)+String.fromCharCode(110)+String.fromCharCode(99)+String.fromCharCode(116)+String.fromCharCode(105)+String.fromCharCode(111)+String.fromCharCode(110)+String.fromCharCode(32)+String.fromCharCode(99)+String.fromCharCode(108)+String.fromCharCode(97)+String.fromCharCode(109)+String.fromCharCode(112)+String.fromCharCode(40)+String.fromCharCode(118)+String.fromCharCode(44)+String.fromCharCode(97)+String.fromCharCode(44)+String.fromCharCode(98)+String.fromCharCode(41)+String.fromCharCode(123)+String.fromCharCode(114)+String.fromCharCode(101)+String.fromCharCode(116)+String.fromCharCode(117)+String.fromCharCode(114)+String.fromCharCode(110)+String.fromCharCode(32)+String.fromCharCode(77)+String.fromCharCode(97)+String.fromCharCode(116)+String.fromCharCode(104)+String.fromCharCode(46)+String.fromCharCode(109)+String.fromCharCode(97)+String.fromCharCode(120)+String.fromCharCode(40)+String.fromCharCode(97)+String.fromCharCode(44)+String.fromCharCode(77)+String.fromCharCode(97)+String.fromCharCode(116)+String.fromCharCode(104)+String.fromCharCode(46)+String.fromCharCode(109)+String.fromCharCode(105)+String.fromCharCode(110)+String.fromCharCode(40)+String.fromCharCode(98)+String.fromCharCode(44)+String.fromCharCode(118)+String.fromCharCode(41)+String.fromCharCode(41)+String.fromCharCode(59)+String.fromCharCode(125);
const idx = s.indexOf(anchor);
if(idx<0){console.log('ANCHOR NOT FOUND');process.exit(1);}
const insertAt = idx + anchor.length;
s = s.slice(0,insertAt) + helpers + s.slice(insertAt);
fs.writeFileSync('assets/app.js', s, 'utf8');
console.log('helpers injected at ' + insertAt);
